# -*- coding: utf-8 -*-
"""РК1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nRLumZon52fcSk09MWJNG4vcLr7eV-PK
"""

import numpy as np
import pandas as pd
from sklearn.feature_selection import SelectKBest, mutual_info_regression
from scipy.stats import boxcox
import matplotlib.pyplot as plt

# Set random seed for reproducibility
np.random.seed(42)

# ============================================
# STEP 1: Generate dataset
# ============================================
n_samples = 500

# Generate features with different distributions
X1 = np.random.exponential(scale=2, size=n_samples)      # right-skewed
X2 = np.random.gamma(2, 2, size=n_samples)               # right-skewed
X3 = np.random.chisquare(3, size=n_samples)              # right-skewed
X4 = np.random.normal(0, 1, size=n_samples)              # normal
X5 = np.random.uniform(-2, 2, size=n_samples)            # uniform

# Target variable: correlated with X1, X2, X4
y = (2 * X1 + 1.5 * X2 + 3 * X4 + np.random.normal(0, 1.5, size=n_samples))

df = pd.DataFrame({
    'feat1': X1,
    'feat2': X2,
    'feat3': X3,
    'feat4': X4,
    'feat5': X5,
    'target': y
})

print("First 5 rows of dataset:")
print(df.head())
print(f"\nDataset shape: {df.shape}")

"""# TASK 1: Box-Cox transformation for a single numerical feature"""

print("\n" + "="*50)
print("TASK 1: Box-Cox Transformation")
print("="*50)

print(f"\nSkewness of 'feat1' before transformation: {df['feat1'].skew():.4f}")

df['feat1_boxcox'], lambda_opt = boxcox(df['feat1'] + 1e-6)  # tiny shift to avoid

print(f"Skewness of 'feat1_boxcox' after transformation: {df['feat1_boxcox'].skew():.4f}")
print(f"Optimal lambda (λ): {lambda_opt:.4f}")

fig, axes = plt.subplots(1, 2, figsize=(10, 3))
axes[0].hist(df['feat1'], bins=30, edgecolor='black', alpha=0.7)
axes[0].set_title('Original feat1 (skewed)')
axes[0].set_xlabel('Value')
axes[0].set_ylabel('Frequency')

axes[1].hist(df['feat1_boxcox'], bins=30, edgecolor='black', alpha=0.7, color='green')
axes[1].set_title('Box-Cox Transformed feat1')
axes[1].set_xlabel('Value')
axes[1].set_ylabel('Frequency')

plt.tight_layout()
plt.show()

"""# TASK 2: Feature selection using SelectKBest with mutual information"""

print("\n" + "="*50)
print("TASK 2: Feature Selection with SelectKBest + Mutual Information")
print("="*50)

X = df[['feat1', 'feat2', 'feat3', 'feat4', 'feat5']]
y = df['target']

# Apply SelectKBest with mutual information, select top 5 features
mi_selector = SelectKBest(score_func=mutual_info_regression, k=5)
mi_selector.fit(X, y)

# Get scores and rankings
mi_scores = mi_selector.scores_
features = X.columns
mi_ranking = pd.DataFrame({
    'feature': features,
    'MI_score': mi_scores,
    'selected': mi_selector.get_support()
}).sort_values('MI_score', ascending=False)

print("\nMutual Information scores (higher = more important):")
print(mi_ranking)

# Get selected features
selected_features = mi_ranking[mi_ranking['selected']]['feature'].tolist()
print(f"\nTop 5 features selected by SelectKBest (based on mutual information): {selected_features}")

# Verify that exactly 5 features were selected
print(f"\nNumber of selected features: {len(selected_features)}")

"""
Experiment: Box-Cox Transformation & Feature Selection using Mutual Information
Dataset: Generated synthetic data with skewed distributions
Additional Task: Histogram for arbitrary column (Group requirement for ИУ5И-22М)
"""

import numpy as np
import pandas as pd
from sklearn.feature_selection import SelectKBest, mutual_info_regression
from scipy.stats import boxcox
import matplotlib.pyplot as plt

# Set random seed for reproducibility
np.random.seed(42)

# ============================================
# STEP 1: Generate dataset
# ============================================
n_samples = 500

# Generate features with different distributions
X1 = np.random.exponential(scale=2, size=n_samples)      # right-skewed
X2 = np.random.gamma(2, 2, size=n_samples)               # right-skewed
X3 = np.random.chisquare(3, size=n_samples)              # right-skewed
X4 = np.random.normal(0, 1, size=n_samples)              # normal
X5 = np.random.uniform(-2, 2, size=n_samples)            # uniform

# Target variable: correlated with X1, X2, X4
y = (2 * X1 + 1.5 * X2 + 3 * X4 + np.random.normal(0, 1.5, size=n_samples))

df = pd.DataFrame({
    'feat1': X1,
    'feat2': X2,
    'feat3': X3,
    'feat4': X4,
    'feat5': X5,
    'target': y
})

print("First 5 rows of dataset:")
print(df.head())
print(f"\nDataset shape: {df.shape}")

# ============================================
# TASK 1: Box-Cox transformation for a single numerical feature
# ============================================
print("\n" + "="*50)
print("TASK 1: Box-Cox Transformation")
print("="*50)

# Choose a skewed feature (feat1)
print(f"\nSkewness of 'feat1' before transformation: {df['feat1'].skew():.4f}")

# Apply Box-Cox transformation (data must be positive)
df['feat1_boxcox'], lambda_opt = boxcox(df['feat1'] + 1e-6)

print(f"Skewness of 'feat1_boxcox' after transformation: {df['feat1_boxcox'].skew():.4f}")
print(f"Optimal lambda (λ): {lambda_opt:.4f}")

# Visualize the transformation effect
fig, axes = plt.subplots(1, 2, figsize=(10, 3))
axes[0].hist(df['feat1'], bins=30, edgecolor='black', alpha=0.7)
axes[0].set_title('Original feat1 (skewed)')
axes[0].set_xlabel('Value')
axes[0].set_ylabel('Frequency')

axes[1].hist(df['feat1_boxcox'], bins=30, edgecolor='black', alpha=0.7, color='green')
axes[1].set_title('Box-Cox Transformed feat1')
axes[1].set_xlabel('Value')
axes[1].set_ylabel('Frequency')

plt.tight_layout()
plt.show()

# ============================================
# TASK 2: Feature selection using SelectKBest with mutual information
# ============================================
print("\n" + "="*50)
print("TASK 2: Feature Selection with SelectKBest + Mutual Information")
print("="*50)

# Prepare features and target
X = df[['feat1', 'feat2', 'feat3', 'feat4', 'feat5']]
y = df['target']

# Apply SelectKBest with mutual information, select top 5 features
mi_selector = SelectKBest(score_func=mutual_info_regression, k=5)
mi_selector.fit(X, y)

# Get scores and rankings
mi_scores = mi_selector.scores_
features = X.columns
mi_ranking = pd.DataFrame({
    'feature': features,
    'MI_score': mi_scores,
    'selected': mi_selector.get_support()
}).sort_values('MI_score', ascending=False)

print("\nMutual Information scores (higher = more important):")
print(mi_ranking)

# Get selected features
selected_features = mi_ranking[mi_ranking['selected']]['feature'].tolist()
print(f"\nTop 5 features selected by SelectKBest (based on mutual information): {selected_features}")
print(f"\nNumber of selected features: {len(selected_features)}")

# Visualize feature scores
plt.figure(figsize=(10, 6))
plt.barh(features, mi_scores, color='skyblue')
plt.xlabel('Mutual Information Score')
plt.title('Feature Scores using Mutual Information')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

# ============================================
# TASK 3: ADDITIONAL REQUIREMENT - Histogram for arbitrary column
# Group: ИУ5И-22М
# ============================================
print("\n" + "="*50)
print("TASK 3: ADDITIONAL REQUIREMENT - Histogram")
print("="*50)

# Choose an arbitrary column (feat2 - gamma distribution)
chosen_column = 'feat2'
print(f"\nPlotting histogram for column: '{chosen_column}'")
print(f"Column description: Gamma-distributed feature with shape=2, scale=2")
print(f"Skewness of '{chosen_column}': {df[chosen_column].skew():.4f}")
print(f"Mean: {df[chosen_column].mean():.4f}")
print(f"Std: {df[chosen_column].std():.4f}")
print(f"Min: {df[chosen_column].min():.4f}")
print(f"Max: {df[chosen_column].max():.4f}")

# Plot histogram
plt.figure(figsize=(8, 5))
plt.hist(df[chosen_column], bins=30, edgecolor='black', alpha=0.7, color='orange')
plt.title(f'Histogram of {chosen_column} (Gamma Distribution)', fontsize=14)
plt.xlabel('Value', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

print("\n" + "="*50)
print("All tasks completed:")
print("✓ Task 1: Box-Cox transformation on feat1")
print("✓ Task 2: Feature selection (SelectKBest + mutual info) - top 5 features")
print("✓ Task 3 (Additional): Histogram for arbitrary column (feat2)")
print("="*50)